#!/bin/bash
script="$0"
script_dir="$(dirname $script)"

echo oc login -u kubeadmin -p $(sh $script_dir/crc-admin-pw) https://api.crc.testing:6443

oc login -u kubeadmin -p $(sh $script_dir/crc-admin-pw) https://api.crc.testing:6443
