apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
        - name: github-runner
          image: jduimovich/github-runner-fd:latest
          env:
            - name: GITHUB_OWNER
              value: jduimovich
            - name: GITHUB_REPOSITORY
              value: https://github.com/jduimovich/runnertest
            - name: GITHUB_PAT
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: pat
